// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9nvHPwZN-2PzUem5lX3luhGoaJAClZkw',
    appId: '1:243034557950:web:192c79c0b97129c03c84af',
    messagingSenderId: '243034557950',
    projectId: 'fir-flutter-codelab-512ef',
    authDomain: 'fir-flutter-codelab-512ef.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-512ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wzBGqIkAYXboWh3u0zKksndq6Cz6oes',
    appId: '1:243034557950:android:37264fc7825adb823c84af',
    messagingSenderId: '243034557950',
    projectId: 'fir-flutter-codelab-512ef',
    storageBucket: 'fir-flutter-codelab-512ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutTY95dO5S3iLgL71EYa0FtMjgNE5PGQ',
    appId: '1:243034557950:ios:795a5f6c4dcd489b3c84af',
    messagingSenderId: '243034557950',
    projectId: 'fir-flutter-codelab-512ef',
    storageBucket: 'fir-flutter-codelab-512ef.appspot.com',
    iosClientId: '243034557950-2pl5atvcpr90pj7ho1a13na991m6caur.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutTY95dO5S3iLgL71EYa0FtMjgNE5PGQ',
    appId: '1:243034557950:ios:795a5f6c4dcd489b3c84af',
    messagingSenderId: '243034557950',
    projectId: 'fir-flutter-codelab-512ef',
    storageBucket: 'fir-flutter-codelab-512ef.appspot.com',
    iosClientId: '243034557950-2pl5atvcpr90pj7ho1a13na991m6caur.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
